#page title
page_title: BulletPrep # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6739197126 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # https://apps.apple.com/us/app/scripture-connect-bible-chat/id6717577481 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=com.alexsyeo.bulletprep # https://forms.gle/qF7qmu2vdotpKRzn7 # Enter Google Play Store URL.
presskit_download_link:
    # https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/icon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: BulletPrep # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: LSAT<sup>®</sup> prep on the go.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
# your_name: Alex Yeo
# your_link: https://emilbaehr.com
# your_city: Copenhagen
email_address: hi@bulletprep.app
# facebook_username:
# instagram_username: alexsyeo
# linkedin_username: alexsyeo
discord_link: https://discord.gg/FFv2htKNQz
# twitter_username: ebaehr
# github_username: alexsyeo
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
    - title: Affordable, Accessible, and Convenient
      description: BulletPrep offers a 3 day free trial, followed by a monthly subscription of $9.99 USD. No LawHub<sup>TM</sup> Advantage membership required. Done with your prep? Cancel anytime!
      fontawesome_icon_name: dollar-sign

    - title: Hundreds of Practice Questions and Explanations
      description: Practice with hundreds of original LSAT<sup>®</sup>-style Logical Reasoning and Reading Comprehension questions created and curated by the team, with more constantly being added.
      fontawesome_icon_name: book-open

    - title: Mobile First
      description: BulletPrep is designed for mobile devices, with a focus on accessibility, convenience, and ease of use. BulletPrep is not meant to be a replacement for other prep resources, but rather a convenient, on-the-go supplement to your prep.
      fontawesome_icon_name: mobile-alt

    - title: AI Study Buddy
      description: Get instant, personalized study advice, explanations, and feedback on your prep, leveraging the latest AI models. If you don't understand an explanation, just ask!
      fontawesome_icon_name: brain

    - title: Contact us anytime
      description: You get a direct communication line with the team via email and Discord to request support, provide feedback, and more. Our team will make sure to respond in a timely manner.
      fontawesome_icon_name: envelope

# Theme Settings
topbar_color: "#191919"
topbar_transparency: .65
topbar_title_color: "#fcfcfc"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#191919"
cover_overlay_transparency: 1.0

device_color: black # Set to: blue, black, yellow, coral or white.

# body_background_color: "#f7ea77"
body_background_color: "#99BBFF"
# body_background_color: "#74c67b"

link_color: "#0661ff"

app_title_color: "#fcfcfc"
app_price_color: "#fcfcfc"
app_description_color: "#fcfcfc"
# app_title_color: "#191919"
# app_price_color: "#191919"
# app_description_color: "#191919"

feature_title_color: "#191919"
feature_text_color: "#191919"

feature_icons_foreground_color: "#fcfcfc"
feature_icons_background_color: "#191919"

social_icons_foreground_color: "#fcfcfc"
social_icons_background_color: "#191919"

footer_text_color: "#191919"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - CNAME

collections:
    pages:
        output: true
        permalink: /:path/

# Markdown rendering
markdown: kramdown
