#page title
page_title: Hello Hendrix # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6499281148 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://forms.gle/qF7qmu2vdotpKRzn7 # Enter Google Play Store URL.
presskit_download_link:
    # https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/icon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Hello Hendrix # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Improve your conversational Korean with AI.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Alex Yeo
# your_link: https://emilbaehr.com
# your_city: Copenhagen
email_address: hi@hellohendrix.app
# facebook_username:
# instagram_username: alexsyeo
linkedin_username: alexsyeo
# twitter_username: ebaehr
# github_username: alexsyeo
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
    - title: Free Trial
      description: Try out the app for free with no limitations for 7 days.
      fontawesome_icon_name: play-circle

    - title: Simulate Conversations
      description: Realistic conversations spanning hundreds of scenarios and topics.
      fontawesome_icon_name: comments

    - title: Real Time Feedback
      description: Real time feedback with useful explanations and suggestions, covering grammar, vocabulary, and more.
      fontawesome_icon_name: info-circle

    - title: On-Demand Translations
      description: Immediate translations for any word or phrase with audio pronunciation.
      fontawesome_icon_name: language

    - title: Realistic Voices
      description: Realistic voices that resemble native Korean speakers.
      fontawesome_icon_name: volume-up

    - title: Premade Flashcards
      description: Hundreds of premade flashcards across all modules so you can learn the essential vocabulary for each topic.
      fontawesome_icon_name: list

    - title: Automatic Flashcard Generation
      description: Automatically-generated flashcards based on real time feedback and translations.
      fontawesome_icon_name: magic

    - title: Direct Communication Line with Developer
      description: Direct communication line with the developer to request support, provide feedback, and more.
      fontawesome_icon_name: envelope

    - title: Continuous Updates
      description: Continuous updates with new content, features, and improvements.
      fontawesome_icon_name: download

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#fcfcfc"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#fbdf56ff"

link_color: "#0661ff"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#191919"
feature_text_color: "#191919"

feature_icons_foreground_color: "#fcfcfc"
feature_icons_background_color: "#191919"

social_icons_foreground_color: "#fcfcfc"
social_icons_background_color: "#191919"

footer_text_color: "#191919"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - CNAME

collections:
    pages:
        output: true
        permalink: /:path/

# Markdown rendering
markdown: kramdown
